---
- name: Get join token from master
  become: false
  remote_user: ubuntu
  shell: microk8s add-node
  register: join_token
  delegate_to: "{{ master_ip }}"

- name: Debug variables
  debug:
    var: master_ip

- name: Debug variables
  debug:
    var: join_token

- name: Join worker node to the cluster
  shell: "microk8s join {{ master_ip }}:25000/{{ join_token }}"